

APP_BASE_URL = "https://email-sum-mcit.streamlit.app/"

# Google (Gmail) – OAuth 2.0 Client of type "Web application"
GOOGLE_CLIENT_ID = "1087347704895-332popcvdk477frp0po25siic79b2lpc.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"

# Microsoft (Azure AD) – App registration
MS_CLIENT_ID = "52f1499e-b53e-46a0-9467-da98c27001d9"
MS_CLIENT_SECRET = "e0e7a8c4-942d-480c-bdd5-43559ce29d30"

MS_TENANT        = "5ccc6ca4-7d74-43dc-9fe9-d4dd59246247" 


#sec id  e0e7a8c4-942d-480c-bdd5-43559ce29d30