[google]
client_id = "1087347704895-332popcvdk477frp0po25siic79b2lpc.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "http://localhost:8501"
scope = "https://www.googleapis.com/auth/gmail.readonly"



